// Mocks generated by Mockito 5.4.6 from annotations
// in my_pill/test/data/providers/settings_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:my_pill/data/models/adherence_record.dart' as _i8;
import 'package:my_pill/data/models/caregiver_link.dart' as _i10;
import 'package:my_pill/data/models/medication.dart' as _i5;
import 'package:my_pill/data/models/reminder.dart' as _i7;
import 'package:my_pill/data/models/schedule.dart' as _i6;
import 'package:my_pill/data/models/user_profile.dart' as _i9;
import 'package:my_pill/data/services/storage_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i2.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Uint8List get encryptionKeyBytes =>
      (super.noSuchMethod(
            Invocation.getter(#encryptionKeyBytes),
            returnValue: _i3.Uint8List(0),
          )
          as _i3.Uint8List);

  @override
  _i4.Future<void> initializeEncryption() =>
      (super.noSuchMethod(
            Invocation.method(#initializeEncryption, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveMedication(_i5.Medication? med) =>
      (super.noSuchMethod(
            Invocation.method(#saveMedication, [med]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.Medication?> getMedication(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMedication, [id]),
            returnValue: _i4.Future<_i5.Medication?>.value(),
          )
          as _i4.Future<_i5.Medication?>);

  @override
  _i4.Future<List<_i5.Medication>> getAllMedications() =>
      (super.noSuchMethod(
            Invocation.method(#getAllMedications, []),
            returnValue: _i4.Future<List<_i5.Medication>>.value(
              <_i5.Medication>[],
            ),
          )
          as _i4.Future<List<_i5.Medication>>);

  @override
  _i4.Future<void> deleteMedication(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMedication, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveSchedule(_i6.Schedule? schedule) =>
      (super.noSuchMethod(
            Invocation.method(#saveSchedule, [schedule]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i6.Schedule?> getSchedule(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getSchedule, [id]),
            returnValue: _i4.Future<_i6.Schedule?>.value(),
          )
          as _i4.Future<_i6.Schedule?>);

  @override
  _i4.Future<List<_i6.Schedule>> getAllSchedules() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSchedules, []),
            returnValue: _i4.Future<List<_i6.Schedule>>.value(<_i6.Schedule>[]),
          )
          as _i4.Future<List<_i6.Schedule>>);

  @override
  _i4.Future<List<_i6.Schedule>> getSchedulesForMedication(
    String? medicationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSchedulesForMedication, [medicationId]),
            returnValue: _i4.Future<List<_i6.Schedule>>.value(<_i6.Schedule>[]),
          )
          as _i4.Future<List<_i6.Schedule>>);

  @override
  _i4.Future<void> deleteSchedule(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSchedule, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveReminder(_i7.Reminder? reminder) =>
      (super.noSuchMethod(
            Invocation.method(#saveReminder, [reminder]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i7.Reminder?> getReminder(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getReminder, [id]),
            returnValue: _i4.Future<_i7.Reminder?>.value(),
          )
          as _i4.Future<_i7.Reminder?>);

  @override
  _i4.Future<List<_i7.Reminder>> getAllReminders() =>
      (super.noSuchMethod(
            Invocation.method(#getAllReminders, []),
            returnValue: _i4.Future<List<_i7.Reminder>>.value(<_i7.Reminder>[]),
          )
          as _i4.Future<List<_i7.Reminder>>);

  @override
  _i4.Future<List<_i7.Reminder>> getRemindersForDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getRemindersForDate, [date]),
            returnValue: _i4.Future<List<_i7.Reminder>>.value(<_i7.Reminder>[]),
          )
          as _i4.Future<List<_i7.Reminder>>);

  @override
  _i4.Future<void> deleteReminder(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteReminder, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteRemindersForMedication(String? medicationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRemindersForMedication, [medicationId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveAdherenceRecord(_i8.AdherenceRecord? record) =>
      (super.noSuchMethod(
            Invocation.method(#saveAdherenceRecord, [record]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i8.AdherenceRecord>> getAdherenceRecords({
    String? medicationId,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAdherenceRecords, [], {
              #medicationId: medicationId,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i4.Future<List<_i8.AdherenceRecord>>.value(
              <_i8.AdherenceRecord>[],
            ),
          )
          as _i4.Future<List<_i8.AdherenceRecord>>);

  @override
  _i4.Future<void> deleteAdherenceRecordsForMedication(String? medicationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAdherenceRecordsForMedication, [
              medicationId,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveUserProfile(_i9.UserProfile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserProfile, [profile]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i9.UserProfile?> getUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, []),
            returnValue: _i4.Future<_i9.UserProfile?>.value(),
          )
          as _i4.Future<_i9.UserProfile?>);

  @override
  _i4.Future<void> saveCaregiverLink(_i10.CaregiverLink? link) =>
      (super.noSuchMethod(
            Invocation.method(#saveCaregiverLink, [link]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i10.CaregiverLink>> getAllCaregiverLinks() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCaregiverLinks, []),
            returnValue: _i4.Future<List<_i10.CaregiverLink>>.value(
              <_i10.CaregiverLink>[],
            ),
          )
          as _i4.Future<List<_i10.CaregiverLink>>);

  @override
  _i4.Future<void> deleteCaregiverLink(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCaregiverLink, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deletePhotoFile(String? photoPath) =>
      (super.noSuchMethod(
            Invocation.method(#deletePhotoFile, [photoPath]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> migrateUnencryptedPhotos() =>
      (super.noSuchMethod(
            Invocation.method(#migrateUnencryptedPhotos, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearUserData() =>
      (super.noSuchMethod(
            Invocation.method(#clearUserData, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
